apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: web-pod
      labels:
        app: myweb
    spec:
      containers:
      - name: h-con
        image: yunchae02/myweb:1

