apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      name: web-pod
      labels:
        app: web-app
    spec:
      containers:
      - name: web-con
        image: yunchae02/myweb:2
        ports:
        - containerPort: 80
