apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: yunchae02/myweb:1
        ports:
        - containerPort: 80
